---
name: metanorma-cache
description: Cache metanorma-related assets (fonts, workgroups)
inputs:
  cache-site-for-manifest:
    description: Path to valid metanorma.yml manifest file
    default: ''
  extra-input:
    description: |
      Comma (or line) separated list of directories that affect metanorma build.
      All paths relative to `cache-site-for-manifest`
    default: ''
  cache-site-path:
    description: Path to the output site directory
    default: '_site'
outputs:
  cache-site-cache-hit:
    description: "True if valid cache exists"

runs:
  using: 'node24'
  main: 'dist/index.cjs'
